name: Build Documentation
description: 'Build Documentation.'

runs:
  using: composite
  steps:
    - name: Install jazzy gem
      shell: bash
      run: |
        gem install mustache -v 1.1.2 --no-document
        gem install jazzy -v 0.15.4 --conservative --no-document

    - name: Build Documentation
      shell: bash
      run: jazzy -o docs

    - name: Validate coverage
      shell: bash
      run: |
        FULLDOC=`jq '.warnings | length == 0' docs/undocumented.json`
        [ $FULLDOC == "true" ]
